---
title: Caça-Fantasmas
hero_image: images/ghostbusters.png
description: Crie um jogo de Caça-Fantasmas!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: green
listed: false
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.2.1
last_tested: 2018-01-01
steps:
  - title: Introdução
  - title: Animando um fantasma
  - title: Fantasmas aleatórios
  - title: Capturando fantasmas
  - title: Adicionando uma pontuação
  - title: Adicionando um cronômetro
  - title: 'Desafio: Mais objetos'
    challenge: true
