---
title: Ghostbusters
hero_image: images/ghostbusters.png
description: Buat game tentang menangkap hantu!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: green
listed: false
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.2.1
last_tested: 2018-01-01
steps:
  - title: Pengantar
  - title: Menganimasikan satu hantu
  - title: Hantu acak
  - title: Menangkap hantu
  - title: Menambahkan skor
  - title: Menambahkan pengatur waktu
  - title: 'Tantangan: benda tambahan'
    challenge: true
